name: GO

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: connect to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend-payment-gateway-hackaton-wri-2023:latest
  
  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Add support OpenSSH
        run: |
          echo "CASignatureAlgorithms +ssh-rsa" >> /etc/ssh/sshd_config
          service ssh restart

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_UNAME }}
          key: ${{ secrets.SSH_PUB_KEY }}
          port: 22
          script: |
            whoami
            docker stop backend-payment-gateway-hackaton-wri-2023 || true && docker docker rm backend-payment-gateway-hackaton-wri-2023 || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-payment-gateway-hackaton-wri-2023:latest
            docker run -p 3000:3000 -d --name backend-payment-gateway-hackaton-wri-2023 ${{ secrets.DOCKER_USERNAME }}/backend-payment-gateway-hackaton-wri-2023:latest
